"""Accruals task (plan.md 6.2).

Select ``booked:false`` vendor bills whose ``service_period`` is the close
period and accrue them Dr expense / Cr ``Liabilities:Accrued:Expenses`` dated the
period end. Bills for a later service period are listed "do not accrue". Any
accrual at/above materiality is flagged and routed to the controller as an open
exception (exercising controls C5 and C9); it is only booked once approved.

Money is always :class:`decimal.Decimal`; never float.
"""
from __future__ import annotations

import json
import re
from decimal import Decimal
from pathlib import Path

import yaml

from .. import ledger
from ..controls import load_company
from ..models import Invoice

PERIOD = "2026-09"
ACCRUAL_DATE = "2026-09-30"
ACCRUED_ACCOUNT = "Liabilities:Accrued:Expenses"
ZERO = Decimal("0.00")


def _repo(repo) -> Path:
    return Path(repo)


def load_invoices(repo=".") -> list[Invoice]:
    """Read data/ap/invoices.json into Invoice records."""
    path = _repo(repo) / "data" / "ap" / "invoices.json"
    raw = json.loads(path.read_text(encoding="utf-8"))
    return [Invoice.from_dict(d) for d in raw]


def _materiality(repo) -> Decimal:
    company = load_company(_repo(repo) / "data" / "company.json")
    return Decimal(str(company.get("materiality", "10000.00")))


def _narration(invoice: Invoice) -> str:
    expense = invoice.account.split(":")[-1]
    return f"Accrue September {expense}"


def prepare(repo=".") -> dict:
    """Deterministic accrual plan -> work/accruals/candidates.json.

    ``accruals``  bills to accrue (``needs_approval`` set when >= materiality).
    ``skipped``   unbooked bills whose service period is not the close period.
    """
    repo = _repo(repo)
    materiality = _materiality(repo)

    accruals: list[dict] = []
    skipped: list[dict] = []
    for inv in load_invoices(repo):
        if inv.booked:
            continue
        if inv.service_period != PERIOD:
            skipped.append({
                "id": inv.id,
                "vendor": inv.vendor,
                "service_period": inv.service_period,
                "reason": f"do not accrue (service_period {inv.service_period})",
            })
            continue
        accruals.append({
            "id": inv.id,
            "vendor": inv.vendor,
            "account": inv.account,
            "amount": str(inv.amount),
            "date": ACCRUAL_DATE,
            "narration": _narration(inv),
            "source": f"data/ap/invoices.json#{inv.id}",
            "needs_approval": inv.amount >= materiality,
        })

    out_dir = repo / "work" / "accruals"
    out_dir.mkdir(parents=True, exist_ok=True)
    payload = {
        "task": "accruals",
        "period": PERIOD,
        "materiality": str(materiality),
        "accruals": accruals,
        "skipped": skipped,
    }
    (out_dir / "candidates.json").write_text(
        json.dumps(payload, indent=2), encoding="utf-8")
    return payload


def _source_invoice(source) -> str:
    """The invoice id encoded in an exception ``source`` (after the ``#``)."""
    return str(source or "").rsplit("#", 1)[-1]


def _exception_id(invoice_id: str) -> str:
    """A stable exception id derived from the invoice id (INV-001 -> AC-001).

    Derived, not positional, so approval state never migrates to another invoice
    when the set or order of material accruals changes between apply runs.
    """
    match = re.search(r"(\d+)$", invoice_id)
    return f"AC-{match.group(1)}" if match else f"AC-{invoice_id}"


def _load_existing_exceptions(path: Path) -> dict:
    """Map invoice id -> {status, reviewer_note} from a prior apply.

    Keyed on the invoice id parsed from ``source`` (a stable identity), so the
    controller's approve/reject decisions follow the invoice they belong to even
    if exception ordering changes on a re-apply.
    """
    if not path.exists():
        return {}
    items = yaml.safe_load(path.read_text(encoding="utf-8")) or []
    state: dict = {}
    for i in items:
        if not isinstance(i, dict):
            continue
        invoice = _source_invoice(i.get("source"))
        if not invoice:
            continue
        state[invoice] = {
            "status": i.get("status", "open"),
            "reviewer_note": i.get("reviewer_note", ""),
        }
    return state


def apply(repo=".") -> dict:
    """Render ledger/2026-09/accruals.beancount and exceptions/accruals.yaml.

    Non-material accruals auto-post. Material accruals become exceptions; each is
    booked only once its exception is ``approved`` (with an ``approved-by`` meta
    so control C5 stays green).
    """
    repo = _repo(repo)
    plan = prepare(repo)

    exc_path = repo / "exceptions" / "accruals.yaml"
    prior = _load_existing_exceptions(exc_path)

    header = (
        ";; ledger/2026-09/accruals.beancount\n"
        ";; Generated by `closeops apply accruals` (plan 6.2). Do not edit by hand.\n"
    )
    blocks: list[str] = []
    exceptions: list[dict] = []
    booked: list[str] = []

    for acc in plan["accruals"]:
        amount = Decimal(acc["amount"])
        postings = [
            (acc["account"], amount),
            (ACCRUED_ACCOUNT, -amount),
        ]
        meta = {
            "source": acc["source"],
            "task": "accruals",
            "invoice": acc["id"],
        }

        if not acc["needs_approval"]:
            blocks.append(ledger.render_entry(
                ACCRUAL_DATE, acc["vendor"], acc["narration"], postings, meta=meta))
            booked.append(acc["id"])
            continue

        # Material accrual -> exception. Preserve any prior review decision,
        # matched by the invoice id (stable) rather than the exception id.
        exc_id = _exception_id(acc["id"])
        state = prior.get(acc["id"], {})
        status = state.get("status", "open")
        reviewer_note = state.get("reviewer_note", "")

        exceptions.append({
            "id": exc_id,
            "task": "accruals",
            "source": acc["source"],
            "issue": (
                f'{acc["id"]} ({amount:.2f} "{acc["vendor"]}") accrual is at/above '
                f'materiality {plan["materiality"]} and needs controller approval'),
            "proposed_entry": {
                "date": ACCRUAL_DATE,
                "narration": acc["narration"],
                "postings": [
                    {"account": acc["account"], "amount": f"{amount:.2f}"},
                    {"account": ACCRUED_ACCOUNT, "amount": f"{-amount:.2f}"},
                ],
            },
            "confidence": "0.90",
            "decided_by": "closeops-decide",
            "trace": "",
            "status": status,
            "reviewer_note": reviewer_note,
        })

        if status == "approved":
            approved_meta = dict(meta)
            approved_meta["approved-by"] = reviewer_note or "controller"
            blocks.append(ledger.render_entry(
                ACCRUAL_DATE, acc["vendor"], acc["narration"], postings,
                meta=approved_meta))
            booked.append(acc["id"])

    out_path = repo / "ledger" / "2026-09" / "accruals.beancount"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(header + "\n" + "\n".join(blocks), encoding="utf-8")

    exc_path.parent.mkdir(parents=True, exist_ok=True)
    exc_path.write_text(
        yaml.safe_dump(exceptions, sort_keys=False, allow_unicode=True),
        encoding="utf-8")

    ok, out = ledger.bean_check(repo / "ledger" / "main.beancount")
    open_count = sum(1 for e in exceptions if e["status"] == "open")
    return {
        "booked": booked,
        "exceptions": len(exceptions),
        "open_exceptions": open_count,
        "bean_check_ok": ok,
        "bean_check_output": out,
    }
